# workmux configuration for TableYeah Admin (Expo/React Native)

# Pane layout: claude agent on left, shell on right
panes:
  - command: <agent>
    focus: true
  - split: horizontal

# File operations
files:
  # Copy env file (each worktree may need unique values)
  copy:
    - .env
  # Symlink node_modules to save disk space
  symlink:
    - node_modules

# Post-create hooks - run npm install to ensure dependencies are linked
post_create:
  - npm install

# Run lint before merging
pre_merge:
  - npm run lint
